spring.application.name=bookmarker-api


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


<<<<<<< HEAD
spring.flyway.locations=classpath:/db/migration/{vendor}


=======
spring.flyway.locations=classpath:/db/migration/{vendor}
>>>>>>> branch 'main' of https://github.com/suho-98/bookmark-api
